### PR TITLE
Fix Issue #5

### PR DESCRIPTION
**Pull request by tuxzz**
Fix Issue #5

### CODE REVIEW

**Comment by evpobr** [comment]
Why this helps on Windows?

**Comment by tuxzz** [comment]
> Why this helps on Windows?

1. By default, the linker cannot find libraries from vcpkg directory, which is variant in different vcpkg installation. If `vcpkg::find_package` found a package successfully, it will emit all necessary linker arguments automataically. So we don't have to add `#[link]` attribute to `lib.rs`.
2. On Windows, if you specified `#[link(name = "sndfile")]`, the linker will find `sndfile.lib` instead of `libsndfile-1.lib`, which is differ from Linux.

**Comment by tuxzz** [comment]
Currently, If `vcpkg::find_package("libsndfile")` cannot find a package, it silently failed.
This feature may make the compilation error hard to locate.
Should we make `vcpkg` as a feature in `Cargo.toml`, then assert the result of `vcpkg::find_package("libsndfile")` in `build.rs`?

**Comment by evpobr** [comment]
>> On Windows, if you specified #[link(name = "sndfile")], the linker will find sndfile.lib instead of libsndfile-1.lib, which is differ from Linux

Current `libsndfile` from `master` branch always produces `sndfile.lib` even if building `libsndfile-1.dll`. Vcpkg port is outdated and i need to fix xiph/flac#203 and microsoft/vcpkg#10756 before updating it.

**Comment by evpobr** [comment]
> Should we make vcpkg as a optional feature in Cargo.toml, then call unwrap() for the result of vcpkg::find_package("libsndfile") in build.rs?

I think so, because we don't have fallback.

**Pull request merged**
